### ISSUE TITLE
All modifiers should not be applied to every list

### ISSUE THREAD

**Issue by tajakobsen** [tajakobsen/vue-mixin-roving-tabindex#1]
Currently all modifiers are applied to every list. Ensure that modifiers are only applied to individual lists.

**Comment by equinusocio** [comment]
@tajakobsen Is this a blocking issue? I'm considering to use this lib for a new project.

**Comment by tajakobsen** [comment]
@equinusocio Can you share some code on what you've tried?

**Comment by equinusocio** [comment]
No sorry, it was my fault. On codesanbox it works. Sorry.
